import html
import io
import uuid

from fastapi import APIRouter, BackgroundTasks, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from crew.research_crew import run_research
from db.adapter import get_pool

router = APIRouter()


class ResearchRequest(BaseModel):
    topic: str


@router.post("/research")
async def start_research(req: ResearchRequest, background_tasks: BackgroundTasks):
    session_id = str(uuid.uuid4())
    pool = get_pool()
    async with pool.acquire() as conn:
        await conn.execute(
            "INSERT INTO sessions (id, topic, status) VALUES ($1, $2, 'running')",
            session_id,
            req.topic,
        )
    background_tasks.add_task(run_research, session_id, req.topic)
    return {"session_id": session_id, "status": "started"}


@router.get("/report/{session_id}")
async def get_report(session_id: str):
    pool = get_pool()
    async with pool.acquire() as conn:
        row = await conn.fetchrow(
            "SELECT * FROM reports WHERE session_id=$1", session_id
        )
    if not row:
        return {"status": "pending"}
    return {
        "status": "complete",
        "content": row["content"],
        "topic": row["topic"],
        "pdf_path": row.get("pdf_path") if isinstance(row, dict) else row["pdf_path"],
    }


_PDF_CSS = """
  body { font-family: 'Helvetica', sans-serif; color: #111; line-height: 1.5; }
  h1 { font-size: 22pt; margin-bottom: 4pt; }
  h2 { font-size: 16pt; margin-top: 18pt; color: #1f3a8a; }
  h3 { font-size: 13pt; margin-top: 12pt; }
  p, li { font-size: 11pt; }
  .meta { color: #555; font-size: 10pt; margin-bottom: 18pt; }
  pre { white-space: pre-wrap; font-family: 'Courier New', monospace; font-size: 10pt; }
"""


def _render_pdf_html(topic: str, content: str) -> str:
    body = html.escape(content or "").replace("\n", "<br/>")
    safe_topic = html.escape(topic or "")
    return f"""<!doctype html><html><head><meta charset="utf-8">
    <style>{_PDF_CSS}</style></head>
    <body><h1>{safe_topic}</h1>
    <div class="meta">Generated by Research Pipeline</div>
    <pre>{body}</pre></body></html>"""


@router.get("/report/{session_id}/pdf")
async def get_report_pdf(session_id: str):
    pool = get_pool()
    async with pool.acquire() as conn:
        row = await conn.fetchrow(
            "SELECT topic, content FROM reports WHERE session_id=$1", session_id
        )
    if not row or not row.get("content"):
        raise HTTPException(status_code=404, detail="Report not ready")

    try:
        from weasyprint import HTML  # lazy: needs GTK on Windows
    except (ImportError, OSError) as e:
        raise HTTPException(
            status_code=503,
            detail=f"PDF rendering unavailable on this host: {e}",
        )

    pdf_bytes = HTML(string=_render_pdf_html(row["topic"], row["content"])).write_pdf()
    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="research-{session_id}.pdf"'
        },
    )


@router.get("/history")
async def get_history():
    pool = get_pool()
    async with pool.acquire() as conn:
        rows = await conn.fetch(
            "SELECT id, topic, status, created_at FROM sessions "
            "ORDER BY created_at DESC LIMIT 20"
        )
    return [dict(r) for r in rows]
